# Generated by Django 6.0.7 on 2026-08-24 20:55

import core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(help_text='Organization that issued the certificate (e.g. Harvard / CS50).', max_length=150)),
                ('image', models.ImageField(help_text='Certificate thumbnail or preview image.', upload_to='certificates/')),
                ('credential_url', models.URLField(help_text='Public verification / certificate link.')),
                ('credential_id', models.CharField(blank=True, help_text='Optional credential ID shown on the certificate.', max_length=120)),
                ('issued_on', models.DateField(blank=True, help_text='Date the certificate was issued.', null=True)),
                ('description', models.CharField(blank=True, help_text='Optional short description shown on the card.', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=True, help_text='Show this certificate on the home page.')),
            ],
            options={
                'ordering': ['display_order', '-issued_on', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('company', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('volunteer', 'Volunteer')], default='full_time', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_working', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('company_website', models.URLField(blank=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='experience/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('achievements', models.TextField(blank=True, help_text='Major accomplishments during this role.')),
            ],
            options={
                'ordering': ['display_order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('full_name_en', models.CharField(max_length=150, null=True)),
                ('full_name_fa', models.CharField(max_length=150, null=True)),
                ('job_title', models.CharField()),
                ('job_title_en', models.CharField(null=True)),
                ('job_title_fa', models.CharField(null=True)),
                ('short_bio', models.TextField()),
                ('short_bio_en', models.TextField(null=True)),
                ('short_bio_fa', models.TextField(null=True)),
                ('about', models.TextField(blank=True)),
                ('about_en', models.TextField(blank=True, null=True)),
                ('about_fa', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('resume', models.FileField(blank=True, help_text='PDF or Word document, max 5 MB.', null=True, upload_to='resume/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'doc', 'docx'), message='Resume must be a PDF or Word document (.pdf, .doc, .docx).'), core.validators.validate_resume_file_size])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('location_en', models.CharField(blank=True, max_length=150, null=True)),
                ('location_fa', models.CharField(blank=True, max_length=150, null=True)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('x', models.URLField(blank=True, verbose_name='X (Twitter)')),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_title_en', models.CharField(blank=True, max_length=70, null=True)),
                ('seo_title_fa', models.CharField(blank=True, max_length=70, null=True)),
                ('seo_description', models.CharField(blank=True)),
                ('seo_description_en', models.CharField(blank=True, null=True)),
                ('seo_description_fa', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_fa', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=255)),
                ('short_description_en', models.CharField(max_length=255, null=True)),
                ('short_description_fa', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_fa', models.TextField(null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('planned', 'Planned')], default='completed', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_featured', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.project')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('title_en', models.CharField(max_length=150, null=True)),
                ('title_fa', models.CharField(max_length=150, null=True)),
                ('short_description', models.CharField(help_text='A short description shown on service cards.', max_length=255)),
                ('short_description_en', models.CharField(help_text='A short description shown on service cards.', max_length=255, null=True)),
                ('short_description_fa', models.CharField(help_text='A short description shown on service cards.', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description.')),
                ('description_en', models.TextField(blank=True, help_text='Optional detailed description.', null=True)),
                ('description_fa', models.TextField(blank=True, help_text='Optional detailed description.', null=True)),
                ('icon', models.CharField(blank=True, choices=[('', 'Default (check)'), ('check', 'Check'), ('code', 'Code'), ('server', 'Server'), ('database', 'Database'), ('terminal', 'Terminal'), ('folder', 'Folder'), ('globe', 'Globe'), ('external', 'External link'), ('python', 'Python'), ('javascript', 'JavaScript'), ('php', 'PHP'), ('django', 'Django'), ('laravel', 'Laravel'), ('wordpress', 'WordPress'), ('github', 'GitHub')], help_text='SVG icon name from the site icon set (e.g. django, server, code).', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('skills', models.ManyToManyField(blank=True, related_name='services', to='core.skill')),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='projects', to='core.skill'),
        ),
    ]
