# Generated by Django 6.0.7 on 2026-08-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_certificate_contactmessage_experience_projectimage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, choices=[('', 'Default (check)'), ('check', 'Check'), ('code', 'Code'), ('server', 'Server'), ('database', 'Database'), ('terminal', 'Terminal'), ('folder', 'Folder'), ('globe', 'Globe'), ('external', 'External link'), ('python', 'Python'), ('javascript', 'JavaScript'), ('php', 'PHP'), ('django', 'Django'), ('laravel', 'Laravel'), ('wordpress', 'WordPress'), ('github', 'GitHub')], help_text='SVG icon name from the site icon set (e.g. django, server, code).', max_length=50),
        ),
    ]
