# Generated by Django 6.0.7 on 2026-08-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_about_en_profile_about_fa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, help_text='Optional detailed description.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_fa',
            field=models.TextField(blank=True, help_text='Optional detailed description.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_en',
            field=models.CharField(help_text='A short description shown on service cards.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_fa',
            field=models.CharField(help_text='A short description shown on service cards.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_fa',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
