# Generated by Django 6.0.7 on 2026-08-24 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_fa', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_fa', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('name_fa', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_fa', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Optional short summary. If empty, one is generated from the content.')),
                ('excerpt_en', models.TextField(blank=True, help_text='Optional short summary. If empty, one is generated from the content.', null=True)),
                ('excerpt_fa', models.TextField(blank=True, help_text='Optional short summary. If empty, one is generated from the content.', null=True)),
                ('content', models.TextField(help_text='Post body written in Markdown.')),
                ('content_en', models.TextField(help_text='Post body written in Markdown.', null=True)),
                ('content_fa', models.TextField(help_text='Post body written in Markdown.', null=True)),
                ('featured_image', models.ImageField(blank=True, help_text='Local upload. Takes precedence over the external URL.', null=True, upload_to='blog/')),
                ('featured_image_url', models.URLField(blank=True, help_text='External image URL (useful for n8n / hosted images).')),
                ('featured_image_alt', models.CharField(blank=True, help_text='Alt text for the featured image (SEO / accessibility).', max_length=200)),
                ('featured_image_alt_en', models.CharField(blank=True, help_text='Alt text for the featured image (SEO / accessibility).', max_length=200, null=True)),
                ('featured_image_alt_fa', models.CharField(blank=True, help_text='Alt text for the featured image (SEO / accessibility).', max_length=200, null=True)),
                ('author_name', models.CharField(blank=True, help_text='Plain-text author. Leave blank to use the site profile name.', max_length=150)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, help_text='Set automatically on first publish; editable for backdating.', null=True)),
                ('seo_title', models.CharField(blank=True, help_text='Optional override for the <title> tag (max ~70 chars).', max_length=70)),
                ('seo_title_en', models.CharField(blank=True, help_text='Optional override for the <title> tag (max ~70 chars).', max_length=70, null=True)),
                ('seo_title_fa', models.CharField(blank=True, help_text='Optional override for the <title> tag (max ~70 chars).', max_length=70, null=True)),
                ('seo_description', models.CharField(blank=True, help_text='Optional meta description (max ~160 chars).', max_length=160)),
                ('seo_description_en', models.CharField(blank=True, help_text='Optional meta description (max ~160 chars).', max_length=160, null=True)),
                ('seo_description_fa', models.CharField(blank=True, help_text='Optional meta description (max ~160 chars).', max_length=160, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.tag')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
