# Generated by Django 6.0.7 on 2026-08-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_fa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=models.TextField(help_text='Post body written in Markdown.', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_fa',
            field=models.TextField(help_text='Post body written in Markdown.', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_en',
            field=models.TextField(blank=True, help_text='Optional short summary. If empty, one is generated from the content.', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_fa',
            field=models.TextField(blank=True, help_text='Optional short summary. If empty, one is generated from the content.', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image_alt_en',
            field=models.CharField(blank=True, help_text='Alt text for the featured image (SEO / accessibility).', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image_alt_fa',
            field=models.CharField(blank=True, help_text='Alt text for the featured image (SEO / accessibility).', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_description_en',
            field=models.CharField(blank=True, help_text='Optional meta description (max ~160 chars).', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_description_fa',
            field=models.CharField(blank=True, help_text='Optional meta description (max ~160 chars).', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_title_en',
            field=models.CharField(blank=True, help_text='Optional override for the <title> tag (max ~70 chars).', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_title_fa',
            field=models.CharField(blank=True, help_text='Optional override for the <title> tag (max ~70 chars).', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_fa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_fa',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
