import tempfile
from io import BytesIO

from django.core.files.uploadedfile import SimpleUploadedFile
from django.test import TestCase, override_settings
from django.urls import reverse
from PIL import Image
from rest_framework.test import APIClient

from blog.models import Category, Post, Tag


def tiny_png(name="cover.png"):
    buffer = BytesIO()
    Image.new("RGB", (8, 8), (20, 80, 160)).save(buffer, format="PNG")
    return SimpleUploadedFile(name, buffer.getvalue(), content_type="image/png")


API_KEY = "test-blog-api-key-not-for-production"


@override_settings(BLOG_API_KEY=API_KEY)
class BlogAPIAuthTests(TestCase):
    def setUp(self):
        self.client = APIClient()
        self.list_url = reverse("api-post-list")

    def test_list_requires_api_key(self):
        response = self.client.get(self.list_url)
        self.assertEqual(response.status_code, 401)

    def test_wrong_api_key_returns_401(self):
        response = self.client.get(
            self.list_url,
            HTTP_X_API_KEY="wrong-key",
        )
        self.assertEqual(response.status_code, 401)

    @override_settings(BLOG_API_KEY="")
    def test_empty_configured_key_rejects_all(self):
        response = self.client.get(
            self.list_url,
            HTTP_X_API_KEY="anything",
        )
        self.assertEqual(response.status_code, 401)

        response = self.client.get(self.list_url)
        self.assertEqual(response.status_code, 401)


@override_settings(BLOG_API_KEY=API_KEY)
class BlogAPICrudTests(TestCase):
    def setUp(self):
        self.client = APIClient()
        self.client.credentials(HTTP_X_API_KEY=API_KEY)
        self.list_url = reverse("api-post-list")

    def test_create_post_with_category_tags_and_https_image(self):
        payload = {
            "title": "Shipping a Django REST blog API",
            "content": "# Hello\n\nMarkdown body.",
            "featured_image_url": "https://example.com/cover.jpg",
            "category": "django",
            "tags": ["python", "django", "n8n"],
            "status": "published",
            "author_name": "Emad",
        }
        response = self.client.post(self.list_url, payload, format="json")
        self.assertEqual(response.status_code, 201, response.data)
        self.assertEqual(response.data["slug"], "shipping-a-django-rest-blog-api")
        self.assertEqual(response.data["status"], "published")
        self.assertEqual(response.data["category"], "django")
        self.assertEqual(set(response.data["tags"]), {"python", "django", "n8n"})
        self.assertEqual(
            response.data["featured_image_url"],
            "https://example.com/cover.jpg",
        )
        self.assertTrue(response.data["url"])

        post = Post.objects.get(slug="shipping-a-django-rest-blog-api")
        self.assertTrue(post.is_published)
        self.assertIsNotNone(post.published_at)

        from django.test import Client

        page = Client().get("/en/blog/")
        self.assertEqual(page.status_code, 200)
        self.assertContains(page, "Shipping a Django REST blog API")

    def test_slug_autogenerated_and_collision_suffix(self):
        Post.objects.create(
            title="Hello World",
            slug="hello-world",
            content="first",
            status=Post.Status.DRAFT,
        )
        response = self.client.post(
            self.list_url,
            {"title": "Hello World", "content": "second"},
            format="json",
        )
        self.assertEqual(response.status_code, 201)
        self.assertEqual(response.data["slug"], "hello-world-2")

    def test_reject_non_http_featured_image_url(self):
        for bad_url in (
            "javascript:alert(1)",
            "data:text/html,hi",
            "ftp://example.com/a.jpg",
        ):
            response = self.client.post(
                self.list_url,
                {
                    "title": "Bad image",
                    "content": "body",
                    "featured_image_url": bad_url,
                },
                format="json",
            )
            self.assertEqual(response.status_code, 400, bad_url)
            self.assertIn("featured_image_url", response.data)

    def test_create_post_with_uploaded_featured_image(self):
        with tempfile.TemporaryDirectory() as media_root:
            with override_settings(MEDIA_ROOT=media_root):
                response = self.client.post(
                    self.list_url,
                    {
                        "title": "Post with uploaded cover",
                        "content": "Markdown body.",
                        "featured_image": tiny_png(),
                        "featured_image_alt": "Blue square cover",
                        "category": "django",
                        "tags": '["python", "n8n"]',
                    },
                    format="multipart",
                )
                self.assertEqual(response.status_code, 201, response.data)
                self.assertTrue(response.data["featured_image"])
                self.assertTrue(response.data["image_url"])
                self.assertIn("/media/blog/", response.data["image_url"])

                post = Post.objects.get(slug="post-with-uploaded-cover")
                self.assertTrue(post.featured_image)
                self.assertEqual(post.image_url, post.featured_image.url)
                self.assertEqual(
                    set(post.tags.values_list("name", flat=True)),
                    {"python", "n8n"},
                )

    def test_reject_invalid_featured_image_upload(self):
        response = self.client.post(
            self.list_url,
            {
                "title": "Bad upload",
                "content": "body",
                "featured_image": SimpleUploadedFile(
                    "cover.txt",
                    b"not-an-image",
                    content_type="text/plain",
                ),
            },
            format="multipart",
        )
        self.assertEqual(response.status_code, 400)
        self.assertIn("featured_image", response.data)

    def test_category_and_tag_normalization(self):
        response = self.client.post(
            self.list_url,
            {
                "title": "Norm one",
                "content": "body",
                "category": "  Django  ",
                "tags": ["  Python  ", "python"],
            },
            format="json",
        )
        self.assertEqual(response.status_code, 201, response.data)
        self.assertEqual(Category.objects.count(), 1)
        self.assertEqual(Tag.objects.count(), 1)
        self.assertEqual(Category.objects.get().name, "Django")
        self.assertEqual(Tag.objects.get().name, "Python")

        response = self.client.post(
            self.list_url,
            {
                "title": "Norm two",
                "content": "body",
                "category": "django",
                "tags": ["PYTHON"],
            },
            format="json",
        )
        self.assertEqual(response.status_code, 201, response.data)
        self.assertEqual(Category.objects.count(), 1)
        self.assertEqual(Tag.objects.count(), 1)

    def test_patch_updates_fields(self):
        create = self.client.post(
            self.list_url,
            {
                "title": "Draft post",
                "content": "original",
                "status": "draft",
            },
            format="json",
        )
        slug = create.data["slug"]
        detail = reverse("api-post-detail", kwargs={"slug": slug})

        response = self.client.patch(
            detail,
            {"content": "updated body", "status": "published"},
            format="json",
        )
        self.assertEqual(response.status_code, 200, response.data)
        self.assertEqual(response.data["content"], "updated body")
        self.assertEqual(response.data["status"], "published")
        self.assertEqual(response.data["title"], "Draft post")

    def test_put_not_allowed(self):
        create = self.client.post(
            self.list_url,
            {"title": "No put", "content": "body"},
            format="json",
        )
        detail = reverse("api-post-detail", kwargs={"slug": create.data["slug"]})
        response = self.client.put(
            detail,
            {"title": "No put", "content": "replaced"},
            format="json",
        )
        self.assertEqual(response.status_code, 405)

    def test_delete_post(self):
        create = self.client.post(
            self.list_url,
            {"title": "Delete me", "content": "body"},
            format="json",
        )
        slug = create.data["slug"]
        detail = reverse("api-post-detail", kwargs={"slug": slug})
        response = self.client.delete(detail)
        self.assertEqual(response.status_code, 204)
        self.assertFalse(Post.objects.filter(slug=slug).exists())


@override_settings(
    BLOG_API_KEY=API_KEY,
    REST_FRAMEWORK={
        "DEFAULT_RENDERER_CLASSES": [
            "rest_framework.renderers.JSONRenderer",
        ],
        "DEFAULT_PARSER_CLASSES": [
            "rest_framework.parsers.JSONParser",
        ],
        "DEFAULT_AUTHENTICATION_CLASSES": [
            "blog.api.authentication.BlogAPIKeyAuthentication",
        ],
        "DEFAULT_PERMISSION_CLASSES": [
            "rest_framework.permissions.IsAuthenticated",
        ],
        "DEFAULT_THROTTLE_CLASSES": [
            "rest_framework.throttling.AnonRateThrottle",
            "blog.api.throttling.BlogAPIWriteThrottle",
            "blog.api.throttling.BlogAPIReadThrottle",
        ],
        "DEFAULT_THROTTLE_RATES": {
            "anon": "10/min",
            "blog_api_write": "2/min",
            "blog_api_read": "60/min",
        },
    },
)
class BlogAPIThrottleTests(TestCase):
    def setUp(self):
        from django.core.cache import cache

        cache.clear()
        self.client = APIClient()
        self.client.credentials(HTTP_X_API_KEY=API_KEY)
        self.list_url = reverse("api-post-list")

    def test_write_throttle_returns_429(self):
        for i in range(2):
            response = self.client.post(
                self.list_url,
                {"title": f"Post {i}", "content": "body"},
                format="json",
            )
            self.assertEqual(response.status_code, 201, response.data)

        response = self.client.post(
            self.list_url,
            {"title": "Too many", "content": "body"},
            format="json",
        )
        self.assertEqual(response.status_code, 429)
